name = input("What is your name? ")
lab_grade = float(input("What is your lab grade? "))
midterm_grade = float(input("What is your midterm grade? "))
final_grade = float(input("What is your final grade? "))
last_score = (lab_grade * 25 / 100) + (midterm_grade * 35 / 100) + (final_grade * 40 / 100)
print('Name:', name)
print('Lab:', lab_grade)
print('Midterm:', midterm_grade)
print('Final:', final_grade)
print('Last score:', last_score)